"""
    Chat

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user_ban import UserBan


class TestUserBan(unittest.TestCase):
    """UserBan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserBan(self):
        """Test UserBan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserBan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
