"""
    Chat

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ban_user_user_ban_put(self):
        """Test case for ban_user_user_ban_put

        Ban User  # noqa: E501
        """
        pass

    def test_create_message_from_user_message_receiver_id_post(self):
        """Test case for create_message_from_user_message_receiver_id_post

        Create Message From User  # noqa: E501
        """
        pass

    def test_create_user_users_post(self):
        """Test case for create_user_users_post

        Create User  # noqa: E501
        """
        pass

    def test_delete_message_by_id_message_message_id_delete(self):
        """Test case for delete_message_by_id_message_message_id_delete

        Delete Message By Id  # noqa: E501
        """
        pass

    def test_get_users_by_status_users_status_status_get(self):
        """Test case for get_users_by_status_users_status_status_get

        Get Users By Status  # noqa: E501
        """
        pass

    def test_kick_user_user_kick_get(self):
        """Test case for kick_user_user_kick_get

        Kick User  # noqa: E501
        """
        pass

    def test_login_user_users_login_post(self):
        """Test case for login_user_users_login_post

        Login User  # noqa: E501
        """
        pass

    def test_read_all_messages_message_get(self):
        """Test case for read_all_messages_message_get

        Read All Messages  # noqa: E501
        """
        pass

    def test_read_messages_to_user_from_date_message_receiver_id_sender_id_from_date_get(self):
        """Test case for read_messages_to_user_from_date_message_receiver_id_sender_id_from_date_get

        Read Messages To User From Date  # noqa: E501
        """
        pass

    def test_read_messages_to_user_from_message_receiver_id_sender_id_get(self):
        """Test case for read_messages_to_user_from_message_receiver_id_sender_id_get

        Read Messages To User From  # noqa: E501
        """
        pass

    def test_read_user_users_user_id_get(self):
        """Test case for read_user_users_user_id_get

        Read User  # noqa: E501
        """
        pass

    def test_read_users_users_get(self):
        """Test case for read_users_users_get

        Read Users  # noqa: E501
        """
        pass

    def test_update_user_status_users_status_put(self):
        """Test case for update_user_status_users_status_put

        Update User Status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
